version: '3.8'

services:
  backend:
    container_name: rci-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
      - .
    environment:
      - NODE_ENV=development

  frontend:
    container_name: rci-client
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
